### ISSUE TITLE
Error setConsoleColor failed

### ISSUE THREAD

**Issue by FrankHovis** [bdring/fluidterm#7]
Windows 11 simply shows the error message:

setConsoleColor failed
..press any key to continue

and exits.

**Comment by MitchBradley** [comment]
I am confused.  setConsoleColor is in the Windows version of FluidTerm, whereas this repo is the Python version.  Base on that, I have no idea which version of fluidterm you are running and where it came from.

**Comment by MitchBradley** [comment]
Nor do I know what kind of window you are trying to run it in.  CMD?  PowerShell?  what?

**Comment by FrankHovis** [comment]
Oh ok. I thought that the readme stating

> Usage
> Windows
> 
> The FluidNC release bundle for Windows includes a precompiled executable "fluidterm.exe...
> 
applied here.
